name: Vercel Production Deployment

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '22.x'
  PNPM_VERSION: '10.x'

permissions:
  contents: read
  deployments: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "ğŸ‰ Starting project deployment!"

      # ãƒªãƒã‚¸ãƒˆãƒªã®ã‚³ãƒ¼ãƒ‰ã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: echo "ğŸ“¥ Code checked out successfully!"

      # ç’°å¢ƒã¨ä¾å­˜é–¢ä¿‚ã‚’ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
      - name: Setup Environment and Install Dependencies
        uses: ./.github/actions/setup-deps
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: echo "ğŸ’¾ Dependencies installed successfully!"

      # Vercel CLIã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
      - name: Install Vercel CLI
        run: |
          echo "ğŸ”„ Installing Vercel CLI..."
          pnpm add --global vercel@latest
      - run: echo "âœ… Vercel CLI installed successfully!"
      # æœ¬ç•ªç’°å¢ƒã®æƒ…å ±ã‚’ãƒ—ãƒ«
      - name: Pull Vercel Environment Information
        run: |
          echo "ğŸ”„ Pulling Vercel environment information..."
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      - run: echo "âœ… Vercel environment information pulled successfully!"

      # æœ¬ç•ªç’°å¢ƒã®ãƒ“ãƒ«ãƒ‰
      - name: Build Project Artifacts
        run: |
          echo "ğŸ—ï¸ Building project for production..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      - run: echo "âœ… Project built successfully!"

      # æœ¬ç•ªç’°å¢ƒã«ãƒ‡ãƒ—ãƒ­ã‚¤
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      - run: echo "âœ… Project deployed successfully!"
